"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const order_controller_1 = require("../controller/order/order.controller");
const requireAuth_1 = require("../middleware/requireAuth");
const router = (0, express_1.Router)();
router.post("/create", order_controller_1.createOrder);
router.get("/get", requireAuth_1.requireAuth, order_controller_1.getOrders);
router.get("/check/:id", order_controller_1.checkOrder);
router.get("/get-for-payment/:id", order_controller_1.getOrderForPayment);
exports.default = router;
