"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const requireAuth_1 = require("../middleware/requireAuth");
const user_controller_1 = require("../controller/user/user.controller");
const router = (0, express_1.Router)();
router.get("/me", requireAuth_1.requireAuth, user_controller_1.getUser);
router.post("/update", requireAuth_1.requireAuth, user_controller_1.updateUser);
router.post("/create-address", requireAuth_1.requireAuth, user_controller_1.createNewAddress);
router.post("/remove-address", requireAuth_1.requireAuth, user_controller_1.removeAddress);
exports.default = router;
